version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      - internal
  app:
    container_name: APIGateway
    expose:
      - '8085'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    networks:
      - internal

networks:
  internal:
    name: internal
    external: true